<?php

namespace deproject\firstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * marego_symfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marego_symfonyRepository extends EntityRepository
{
}
